# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  site-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: site
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-builder"
            git config user.name "ci-builder"
      - add_ssh_keys:
          fingerprints:
            - "83:92:4b:e9:9f:eb:22:6c:dd:14:89:f1:85:c3:a0:84"
      - run:
          name: Deploy site to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist site/


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-page:
    jobs:
      - site-deploy:
        filters:
          branches:
            only: main
